### ISSUE TITLE
Adapt previous gap analysis work to 5 GA templates.

### ISSUE THREAD

**Issue by r12a** [w3c/iip#1]
Akshat Joshi is adapting material from a previous CDAC gap analysis effort to fit the standard templates used by the TF.

Languages include: 
Devanagari, Bengali, Tamil, Gujarati, Gurmukhi

**Comment by r12a** [comment]
@akshatsj

**Comment by r12a** [comment]
I think this work has been done, so we can close this issue(?)

**Comment by akshatsj** [comment]
Yes, I think we can close this...

**Comment by nehagk** [comment]
Yes Richard. Please close it.
