### ISSUE TITLE
Incorrect language tag?

### ISSUE THREAD

**Issue by xfq** [w3c/iip#120]
The language tag `km` is used in the [Bengali](https://github.com/w3c/iip/blob/8799d7803faec80cd291c5d88db02dc10cada077/bengali/index.html#L231), [Devanagari](https://github.com/w3c/iip/blob/8799d7803faec80cd291c5d88db02dc10cada077/devanagari/index.html#L214), and [Tamil](https://github.com/w3c/iip/blob/8799d7803faec80cd291c5d88db02dc10cada077/tamil/index.html#L197) layout requirements, but it seems that this subtag should be used for Khmer.

**Comment by xfq** [comment]
Also, the language tag `hi` is used in the [Bengali](https://github.com/w3c/iip/blob/8799d7803faec80cd291c5d88db02dc10cada077/bengali/index.html#L138) layout requirements, but it seems that this subtag should be used for Hindi.

**Comment by r12a** [comment]
Thanks for noticing that.  Should now be fixed in https://github.com/w3c/iip/commit/99951efc7323da506ec5848f9c5330d29026714d.
