### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xfq** [w3c/iip#135]
https://www.w3.org/International/ilreq/tamil/#h_script_overview

> There are also [independent vowels](https://r12a.github.io/scripts/glossary/index.html#independentvowel), one for each vowel sound, including the inherent vowel, and these are used to write all [standalone vowel](https://r12a.github.io/scripts/glossary/index.html#standalonevowel) sounds.

The link to [standalone vowel](https://r12a.github.io/scripts/glossary/index.html#standalonevowel) is broken. We should change it to https://www.w3.org/TR/i18n-glossary/#dfn-standalone-vowel

**Comment by r12a** [comment]
These links were written before the i18n glossary existed. I think all of these glossary links need to point to the W3C I18n glossary if there is an appropriate entry, rather than to my page.
