### ISSUE TITLE
Editorial issue

### ISSUE THREAD

**Issue by xfq** [w3c/iip#141]
https://www.w3.org/TR/beng-lreq/#h_about_this_document

> The document focuses on typographic layout issues. For a deeper understanding of the Bengali script and how it works see XX_ORTHOG Orthography Notes, which includes topics such as: [Phonology](https://r12a.github.io/scripts/beng/bn.html#phonology), [Vowels](https://r12a.github.io/scripts/beng/bn.html#vowels), [Consonants](https://r12a.github.io/scripts/beng/bn.html#consonants), [Encoding choices](https://r12a.github.io/scripts/beng/bn.html#encoding), and [Numbers](https://r12a.github.io/scripts/beng/bn.html#numbers).

"XX_ORTHOG" should be Bengali/Bangla.

**Comment by r12a** [comment]
Fixed.
